- hosts: dev

  tasks:
    - name: Mise à jour apt-get
      apt:
        update_cache: yes

    - name: Installer dépendances système
      apt:
        name: [git, python3, nginx]
        state: present

    - name: Cloner le dépôt
      git:
        repo: "https://github.com/jamesdeoliveira78/projet.git"
        dest: /opt/app

    - name: Installer requirements si besoin
      pip:
        requirements: /opt/app/requirements.txt
      when: 
        - ansible_facts.packages['python3-pip'] is defined

    - name: Lancer l'app
      shell: python3 /opt/app/app.py > /var/log/app.log 2>&1 &
